version: '3.5'
services:
  postgres:
    container_name: postgres_music
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: music123
      POSTGRES_DB: music_app
      PGDATA: /data/postgres
    volumes:
       - postgres-db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - music-networks

  redis:
    container_name: redis_music_queue
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - music-networks

  golang_app:
    container_name: go-be
    build: .
    ports:
      - "8080:8080"
    networks:
      - music-networks
    depends_on:
      - redis
      - postgres


networks:
  music-networks:
    driver: bridge

volumes:
  postgres-db:
    driver: local
