// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: categories_query.sql

package sqlc

import (
	"context"
)

const createSongCategories = `-- name: CreateSongCategories :one
INSERT INTO categories (name) VALUES ($1) RETURNING id, name, created_at
`

func (q *Queries) CreateSongCategories(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRow(ctx, createSongCategories, name)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getSongCategories = `-- name: GetSongCategories :many
SELECT id, name, created_at FROM categories
`

func (q *Queries) GetSongCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, getSongCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
