// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: playlist_query.sql

package sqlc

import (
	"context"
)

const addSongToPlaylist = `-- name: AddSongToPlaylist :exec
INSERT INTO playlist_song (song_id, playlist_id)
VALUES ($1, $2)
`

type AddSongToPlaylistParams struct {
	SongID     int32 `json:"song_id"`
	PlaylistID int32 `json:"playlist_id"`
}

func (q *Queries) AddSongToPlaylist(ctx context.Context, arg AddSongToPlaylistParams) error {
	_, err := q.db.Exec(ctx, addSongToPlaylist, arg.SongID, arg.PlaylistID)
	return err
}

const checkOwnerPlaylist = `-- name: CheckOwnerPlaylist :one
SELECT account_id, id FROM playlist WHERE account_id = $1 and id = $2
`

type CheckOwnerPlaylistParams struct {
	AccountID int32 `json:"account_id"`
	ID        int32 `json:"id"`
}

type CheckOwnerPlaylistRow struct {
	AccountID int32 `json:"account_id"`
	ID        int32 `json:"id"`
}

func (q *Queries) CheckOwnerPlaylist(ctx context.Context, arg CheckOwnerPlaylistParams) (CheckOwnerPlaylistRow, error) {
	row := q.db.QueryRow(ctx, checkOwnerPlaylist, arg.AccountID, arg.ID)
	var i CheckOwnerPlaylistRow
	err := row.Scan(&i.AccountID, &i.ID)
	return i, err
}

const checkSongInPlaylist = `-- name: CheckSongInPlaylist :one
SELECT count(*) 
FROM playlist_song
where song_id = $1 and playlist_id = $2
`

type CheckSongInPlaylistParams struct {
	SongID     int32 `json:"song_id"`
	PlaylistID int32 `json:"playlist_id"`
}

func (q *Queries) CheckSongInPlaylist(ctx context.Context, arg CheckSongInPlaylistParams) (int64, error) {
	row := q.db.QueryRow(ctx, checkSongInPlaylist, arg.SongID, arg.PlaylistID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlaylist = `-- name: CreatePlaylist :one
INSERT INTO playlist (account_id, name)
VALUES($1, $2) RETURNING id, name, account_id, description, created_at
`

type CreatePlaylistParams struct {
	AccountID int32  `json:"account_id"`
	Name      string `json:"name"`
}

func (q *Queries) CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (Playlist, error) {
	row := q.db.QueryRow(ctx, createPlaylist, arg.AccountID, arg.Name)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AccountID,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deletePlaylist = `-- name: DeletePlaylist :exec
DELETE FROM playlist where account_id = $1 and id = $2
`

type DeletePlaylistParams struct {
	AccountID int32 `json:"account_id"`
	ID        int32 `json:"id"`
}

func (q *Queries) DeletePlaylist(ctx context.Context, arg DeletePlaylistParams) error {
	_, err := q.db.Exec(ctx, deletePlaylist, arg.AccountID, arg.ID)
	return err
}

const getPlaylistofUser = `-- name: GetPlaylistofUser :many
SELECT id, name, account_id, description, created_at FROM playlist where account_id = $1
`

func (q *Queries) GetPlaylistofUser(ctx context.Context, accountID int32) ([]Playlist, error) {
	rows, err := q.db.Query(ctx, getPlaylistofUser, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Playlist{}
	for rows.Next() {
		var i Playlist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AccountID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongInPlaylist = `-- name: GetSongInPlaylist :many
SELECT s.id, s.name, s.thumbnail, s.path, s.lyrics, s.duration, s.release_date, s.created_at, s.updated_at from playlist_song p INNER JOIN songs s ON p.song_id = s.id WHERE p.playlist_id = $1
`

func (q *Queries) GetSongInPlaylist(ctx context.Context, playlistID int32) ([]Song, error) {
	rows, err := q.db.Query(ctx, getSongInPlaylist, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Song{}
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Thumbnail,
			&i.Path,
			&i.Lyrics,
			&i.Duration,
			&i.ReleaseDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSongFromPlaylist = `-- name: RemoveSongFromPlaylist :exec
DELETE FROM playlist_song where playlist_id = $1 and song_id = $2
`

type RemoveSongFromPlaylistParams struct {
	PlaylistID int32 `json:"playlist_id"`
	SongID     int32 `json:"song_id"`
}

func (q *Queries) RemoveSongFromPlaylist(ctx context.Context, arg RemoveSongFromPlaylistParams) error {
	_, err := q.db.Exec(ctx, removeSongFromPlaylist, arg.PlaylistID, arg.SongID)
	return err
}

const updatePlaylist = `-- name: UpdatePlaylist :one
UPDATE  playlist 
SET name = $1
WHERE id = $2 and account_id = $3
RETURNING id, name, account_id, description, created_at
`

type UpdatePlaylistParams struct {
	Name      string `json:"name"`
	ID        int32  `json:"id"`
	AccountID int32  `json:"account_id"`
}

func (q *Queries) UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) (Playlist, error) {
	row := q.db.QueryRow(ctx, updatePlaylist, arg.Name, arg.ID, arg.AccountID)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AccountID,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
