// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: song_query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	type_custom "music-app-backend/db/type"
)

const associateSongArtist = `-- name: AssociateSongArtist :exec
INSERT INTO songs_artist (song_id, artist_id, owner) VALUES ($1, $2, true)
`

type AssociateSongArtistParams struct {
	SongID   int32 `json:"song_id"`
	ArtistID int32 `json:"artist_id"`
}

func (q *Queries) AssociateSongArtist(ctx context.Context, arg AssociateSongArtistParams) error {
	_, err := q.db.Exec(ctx, associateSongArtist, arg.SongID, arg.ArtistID)
	return err
}

const createSong = `-- name: CreateSong :one
INSERT INTO songs (
    name,
    thumbnail,
    path,
    lyrics,
    duration,
    release_date
) VALUES (
    $1, 
    $2, 
    $3, 
    $4, 
    $5, 
    $6
) RETURNING id, name, thumbnail, path, lyrics, duration, release_date, created_at, updated_at
`

type CreateSongParams struct {
	Name        string      `json:"name"`
	Thumbnail   pgtype.Text `json:"thumbnail"`
	Path        pgtype.Text `json:"path"`
	Lyrics      pgtype.Text `json:"lyrics"`
	Duration    pgtype.Int4 `json:"duration"`
	ReleaseDate pgtype.Date `json:"release_date"`
}

func (q *Queries) CreateSong(ctx context.Context, arg CreateSongParams) (Song, error) {
	row := q.db.QueryRow(ctx, createSong,
		arg.Name,
		arg.Thumbnail,
		arg.Path,
		arg.Lyrics,
		arg.Duration,
		arg.ReleaseDate,
	)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Thumbnail,
		&i.Path,
		&i.Lyrics,
		&i.Duration,
		&i.ReleaseDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSong = `-- name: DeleteSong :exec
DELETE FROM songs  WHERE id = $1
`

func (q *Queries) DeleteSong(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSong, id)
	return err
}

const getRandomSong = `-- name: GetRandomSong :many
SELECT s.id, s.name, s.thumbnail, s.path, s.lyrics, s.duration, s.release_date, s.created_at, s.updated_at,
CASE
    WHEN COUNT(a.id) > 0 THEN jsonb_agg(jsonb_build_object('name', a.name, 'id', a.id, 'avatar_url', a.avatar_url))
    ELSE '[]'::jsonb
END AS artists 
FROM songs s
LEFT JOIN songs_artist sa on s.id = sa.song_id
LEFT JOIN artist a on a.id = sa.artist_id
GROUP BY s.id
Order by RANDOM()
limit 15
`

type GetRandomSongRow struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Thumbnail   pgtype.Text      `json:"thumbnail"`
	Path        pgtype.Text      `json:"path"`
	Lyrics      pgtype.Text      `json:"lyrics"`
	Duration    pgtype.Int4      `json:"duration"`
	ReleaseDate pgtype.Date      `json:"release_date"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	Artists     type_custom.JSON `json:"artists"`
}

func (q *Queries) GetRandomSong(ctx context.Context) ([]GetRandomSongRow, error) {
	rows, err := q.db.Query(ctx, getRandomSong)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRandomSongRow{}
	for rows.Next() {
		var i GetRandomSongRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Thumbnail,
			&i.Path,
			&i.Lyrics,
			&i.Duration,
			&i.ReleaseDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Artists,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongByID = `-- name: GetSongByID :one

SELECT s.id, s.name, s.thumbnail, s.path, s.lyrics, s.duration, s.release_date, s.created_at, s.updated_at,
CASE
    WHEN COUNT(a.id) > 0 THEN jsonb_agg(jsonb_build_object('name', a.name, 'id', a.id, 'avatar_url', a.avatar_url))
    ELSE '[]'::jsonb
END AS artists 
FROM songs s
LEFT JOIN songs_artist sa on s.id = sa.song_id
LEFT JOIN artist a on a.id = sa.artist_id
WHERE s.id = $1
GROUP BY s.id
`

type GetSongByIDRow struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Thumbnail   pgtype.Text      `json:"thumbnail"`
	Path        pgtype.Text      `json:"path"`
	Lyrics      pgtype.Text      `json:"lyrics"`
	Duration    pgtype.Int4      `json:"duration"`
	ReleaseDate pgtype.Date      `json:"release_date"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	Artists     type_custom.JSON `json:"artists"`
}

func (q *Queries) GetSongByID(ctx context.Context, id int32) (GetSongByIDRow, error) {
	row := q.db.QueryRow(ctx, getSongByID, id)
	var i GetSongByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Thumbnail,
		&i.Path,
		&i.Lyrics,
		&i.Duration,
		&i.ReleaseDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Artists,
	)
	return i, err
}

const getSongBySongCategory = `-- name: GetSongBySongCategory :many
SELECT s.id, s.name, s.thumbnail, s.path, s.lyrics, s.duration, s.release_date, s.created_at, s.updated_at,
CASE
    WHEN COUNT(a.id) > 0 THEN jsonb_agg(jsonb_build_object('name', a.name, 'id', a.id, 'avatar_url', a.avatar_url))
    ELSE '[]'::jsonb
END AS artists 
FROM songs s
LEFT JOIN songs_artist sa on s.id = sa.song_id
LEFT JOIN artist a on a.id = sa.artist_id
WHERE s.id in (
    SELECT song_id from song_categories WHERE category_id = $1
) 
GROUP BY s.id
LIMIT COALESCE($3::int, 50)
OFFSET COALESCE($2::int, 0)
`

type GetSongBySongCategoryParams struct {
	CategoryID int32 `json:"category_id"`
	Start      int32 `json:"start"`
	Size       int32 `json:"size"`
}

type GetSongBySongCategoryRow struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Thumbnail   pgtype.Text      `json:"thumbnail"`
	Path        pgtype.Text      `json:"path"`
	Lyrics      pgtype.Text      `json:"lyrics"`
	Duration    pgtype.Int4      `json:"duration"`
	ReleaseDate pgtype.Date      `json:"release_date"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	Artists     type_custom.JSON `json:"artists"`
}

func (q *Queries) GetSongBySongCategory(ctx context.Context, arg GetSongBySongCategoryParams) ([]GetSongBySongCategoryRow, error) {
	rows, err := q.db.Query(ctx, getSongBySongCategory, arg.CategoryID, arg.Start, arg.Size)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSongBySongCategoryRow{}
	for rows.Next() {
		var i GetSongBySongCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Thumbnail,
			&i.Path,
			&i.Lyrics,
			&i.Duration,
			&i.ReleaseDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Artists,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongOfArtist = `-- name: GetSongOfArtist :many

SELECT s.id, s.name, s.thumbnail, s.path, s.lyrics, s.duration, s.release_date, s.created_at, s.updated_at,
CASE
    WHEN COUNT(a.id) > 0 THEN jsonb_agg(jsonb_build_object('name', a.name, 'id', a.id, 'avatar_url', a.avatar_url))
    ELSE '[]'::jsonb
END AS artists 
FROM songs s
LEFT JOIN songs_artist sa on s.id = sa.song_id
LEFT JOIN artist a on a.id = sa.artist_id
WHERE a.id = $1
GROUP BY s.id
OFFSET COALESCE($2::int, 0)
LIMIT COALESCE($3::int, 50)
`

type GetSongOfArtistParams struct {
	ID    int32 `json:"id"`
	Start int32 `json:"start"`
	Size  int32 `json:"size"`
}

type GetSongOfArtistRow struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Thumbnail   pgtype.Text      `json:"thumbnail"`
	Path        pgtype.Text      `json:"path"`
	Lyrics      pgtype.Text      `json:"lyrics"`
	Duration    pgtype.Int4      `json:"duration"`
	ReleaseDate pgtype.Date      `json:"release_date"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	Artists     type_custom.JSON `json:"artists"`
}

func (q *Queries) GetSongOfArtist(ctx context.Context, arg GetSongOfArtistParams) ([]GetSongOfArtistRow, error) {
	rows, err := q.db.Query(ctx, getSongOfArtist, arg.ID, arg.Start, arg.Size)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSongOfArtistRow{}
	for rows.Next() {
		var i GetSongOfArtistRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Thumbnail,
			&i.Path,
			&i.Lyrics,
			&i.Duration,
			&i.ReleaseDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Artists,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongs = `-- name: GetSongs :many

SELECT s.id, s.name, s.thumbnail, s.path, s.lyrics, s.duration, s.release_date, s.created_at, s.updated_at,
CASE
    WHEN COUNT(a.id) > 0 THEN jsonb_agg(jsonb_build_object('name', a.name, 'id', a.id, 'avatar_url', a.avatar_url))
    ELSE '[]'::jsonb
END AS artists 
FROM songs s
LEFT JOIN songs_artist sa on s.id = sa.song_id
LEFT JOIN artist a on a.id = sa.artist_id
GROUP BY s.id
OFFSET COALESCE($1::int, 0)
LIMIT COALESCE($2::int, 50)
`

type GetSongsParams struct {
	Start int32 `json:"start"`
	Size  int32 `json:"size"`
}

type GetSongsRow struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Thumbnail   pgtype.Text      `json:"thumbnail"`
	Path        pgtype.Text      `json:"path"`
	Lyrics      pgtype.Text      `json:"lyrics"`
	Duration    pgtype.Int4      `json:"duration"`
	ReleaseDate pgtype.Date      `json:"release_date"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	Artists     type_custom.JSON `json:"artists"`
}

func (q *Queries) GetSongs(ctx context.Context, arg GetSongsParams) ([]GetSongsRow, error) {
	rows, err := q.db.Query(ctx, getSongs, arg.Start, arg.Size)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSongsRow{}
	for rows.Next() {
		var i GetSongsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Thumbnail,
			&i.Path,
			&i.Lyrics,
			&i.Duration,
			&i.ReleaseDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Artists,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAssociateSongArtist = `-- name: RemoveAssociateSongArtist :exec

DELETE FROM songs_artist  WHERE artist_id = $1 AND song_id = $2
`

type RemoveAssociateSongArtistParams struct {
	ArtistID int32 `json:"artist_id"`
	SongID   int32 `json:"song_id"`
}

func (q *Queries) RemoveAssociateSongArtist(ctx context.Context, arg RemoveAssociateSongArtistParams) error {
	_, err := q.db.Exec(ctx, removeAssociateSongArtist, arg.ArtistID, arg.SongID)
	return err
}

const searchSong = `-- name: SearchSong :many
SELECT s.id, s.name, s.thumbnail, s.path, s.lyrics, s.duration, s.release_date, s.created_at, s.updated_at,
CASE
    WHEN COUNT(a.id) > 0 THEN jsonb_agg(jsonb_build_object('name', a.name, 'id', a.id, 'avatar_url', a.avatar_url))
    ELSE '[]'::jsonb
END AS artists 
FROM songs s
LEFT JOIN songs_artist sa on s.id = sa.song_id
LEFT JOIN artist a on a.id = sa.artist_id
where s.name ilike $1 || '%'
GROUP BY s.id
OFFSET COALESCE($2::int, 0)
LIMIT COALESCE($3::int, 50)
`

type SearchSongParams struct {
	Search pgtype.Text `json:"search"`
	Start  int32       `json:"start"`
	Size   int32       `json:"size"`
}

type SearchSongRow struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Thumbnail   pgtype.Text      `json:"thumbnail"`
	Path        pgtype.Text      `json:"path"`
	Lyrics      pgtype.Text      `json:"lyrics"`
	Duration    pgtype.Int4      `json:"duration"`
	ReleaseDate pgtype.Date      `json:"release_date"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	Artists     type_custom.JSON `json:"artists"`
}

func (q *Queries) SearchSong(ctx context.Context, arg SearchSongParams) ([]SearchSongRow, error) {
	rows, err := q.db.Query(ctx, searchSong, arg.Search, arg.Start, arg.Size)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchSongRow{}
	for rows.Next() {
		var i SearchSongRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Thumbnail,
			&i.Path,
			&i.Lyrics,
			&i.Duration,
			&i.ReleaseDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Artists,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssociateSongArtist = `-- name: UpdateAssociateSongArtist :exec
UPDATE  songs_artist  SET artist_id =$1
WHERE song_id = $2
`

type UpdateAssociateSongArtistParams struct {
	ArtistID int32 `json:"artist_id"`
	SongID   int32 `json:"song_id"`
}

func (q *Queries) UpdateAssociateSongArtist(ctx context.Context, arg UpdateAssociateSongArtistParams) error {
	_, err := q.db.Exec(ctx, updateAssociateSongArtist, arg.ArtistID, arg.SongID)
	return err
}

const updateSong = `-- name: UpdateSong :exec

UPDATE songs 
SET name = $1, thumbnail = $2, 
path = $3, lyrics = $4, duration = $5, release_date = $6
WHERE id = $7
`

type UpdateSongParams struct {
	Name        string      `json:"name"`
	Thumbnail   pgtype.Text `json:"thumbnail"`
	Path        pgtype.Text `json:"path"`
	Lyrics      pgtype.Text `json:"lyrics"`
	Duration    pgtype.Int4 `json:"duration"`
	ReleaseDate pgtype.Date `json:"release_date"`
	ID          int32       `json:"id"`
}

func (q *Queries) UpdateSong(ctx context.Context, arg UpdateSongParams) error {
	_, err := q.db.Exec(ctx, updateSong,
		arg.Name,
		arg.Thumbnail,
		arg.Path,
		arg.Lyrics,
		arg.Duration,
		arg.ReleaseDate,
		arg.ID,
	)
	return err
}
