// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: statics_query.sql

package sqlc

import (
	"context"
)

const statistics = `-- name: Statistics :one
SELECT
    (SELECT COUNT(*) FROM artist) AS total_artists,
    (SELECT COUNT(*) FROM accounts) AS total_users,
    (SELECT COUNT(*) FROM songs) AS total_songs
`

type StatisticsRow struct {
	TotalArtists int64 `json:"total_artists"`
	TotalUsers   int64 `json:"total_users"`
	TotalSongs   int64 `json:"total_songs"`
}

func (q *Queries) Statistics(ctx context.Context) (StatisticsRow, error) {
	row := q.db.QueryRow(ctx, statistics)
	var i StatisticsRow
	err := row.Scan(&i.TotalArtists, &i.TotalUsers, &i.TotalSongs)
	return i, err
}
